//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazDATMA.GrupoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.datmasoft.datma.pe/", ConfigurationName="GrupoWS.GrupoWS")]
    public interface GrupoWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.insertarGrupoResponse insertarGrupo(InterfazDATMA.GrupoWS.insertarGrupoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.insertarGrupoResponse> insertarGrupoAsync(InterfazDATMA.GrupoWS.insertarGrupoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.eliminarGrupoResponse eliminarGrupo(InterfazDATMA.GrupoWS.eliminarGrupoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.eliminarGrupoResponse> eliminarGrupoAsync(InterfazDATMA.GrupoWS.eliminarGrupoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/modificarGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/modificarGrupoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.modificarGrupoResponse modificarGrupo(InterfazDATMA.GrupoWS.modificarGrupoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/modificarGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/modificarGrupoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.modificarGrupoResponse> modificarGrupoAsync(InterfazDATMA.GrupoWS.modificarGrupoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoTutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.eliminarGrupoTutorResponse eliminarGrupoTutor(InterfazDATMA.GrupoWS.eliminarGrupoTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoTutorResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.eliminarGrupoTutorResponse> eliminarGrupoTutorAsync(InterfazDATMA.GrupoWS.eliminarGrupoTutorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoPsicologoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoPsicologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.insertarGrupoPsicologoResponse insertarGrupoPsicologo(InterfazDATMA.GrupoWS.insertarGrupoPsicologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoPsicologoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoPsicologoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.insertarGrupoPsicologoResponse> insertarGrupoPsicologoAsync(InterfazDATMA.GrupoWS.insertarGrupoPsicologoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoPsicologoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoPsicologoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.eliminarGrupoPsicologoResponse eliminarGrupoPsicologo(InterfazDATMA.GrupoWS.eliminarGrupoPsicologoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoPsicologoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/eliminarGrupoPsicologoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.eliminarGrupoPsicologoResponse> eliminarGrupoPsicologoAsync(InterfazDATMA.GrupoWS.eliminarGrupoPsicologoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/listarPsicologosPorIdGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/listarPsicologosPorIdGrupoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoResponse listarPsicologosPorIdGrupo(InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/listarPsicologosPorIdGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/listarPsicologosPorIdGrupoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoResponse> listarPsicologosPorIdGrupoAsync(InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/modificarGrupoTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/modificarGrupoTutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.modificarGrupoTutorResponse modificarGrupoTutor(InterfazDATMA.GrupoWS.modificarGrupoTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/modificarGrupoTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/modificarGrupoTutorResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.modificarGrupoTutorResponse> modificarGrupoTutorAsync(InterfazDATMA.GrupoWS.modificarGrupoTutorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoTutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.insertarGrupoTutorResponse insertarGrupoTutor(InterfazDATMA.GrupoWS.insertarGrupoTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/insertarGrupoTutorResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.insertarGrupoTutorResponse> insertarGrupoTutorAsync(InterfazDATMA.GrupoWS.insertarGrupoTutorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/listarTutoresPorIdGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/listarTutoresPorIdGrupoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoResponse listarTutoresPorIdGrupo(InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/listarTutoresPorIdGrupoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/listarTutoresPorIdGrupoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoResponse> listarTutoresPorIdGrupoAsync(InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/listarGrupoPorIdCursoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/listarGrupoPorIdCursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.GrupoWS.listarGrupoPorIdCursoResponse listarGrupoPorIdCurso(InterfazDATMA.GrupoWS.listarGrupoPorIdCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/GrupoWS/listarGrupoPorIdCursoRequest", ReplyAction="http://services.datmasoft.datma.pe/GrupoWS/listarGrupoPorIdCursoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.listarGrupoPorIdCursoResponse> listarGrupoPorIdCursoAsync(InterfazDATMA.GrupoWS.listarGrupoPorIdCursoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class grupo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantInfantesField;
        
        private tutor[] cuidadoresField;
        
        private curso cursoField;
        
        private int idGrupoField;
        
        private int maxCantCuidadoresField;
        
        private string nombrePromocionField;
        
        private psicologo[] psicologosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantInfantes {
            get {
                return this.cantInfantesField;
            }
            set {
                this.cantInfantesField = value;
                this.RaisePropertyChanged("cantInfantes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cuidadores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public tutor[] cuidadores {
            get {
                return this.cuidadoresField;
            }
            set {
                this.cuidadoresField = value;
                this.RaisePropertyChanged("cuidadores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public curso curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idGrupo {
            get {
                return this.idGrupoField;
            }
            set {
                this.idGrupoField = value;
                this.RaisePropertyChanged("idGrupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int maxCantCuidadores {
            get {
                return this.maxCantCuidadoresField;
            }
            set {
                this.maxCantCuidadoresField = value;
                this.RaisePropertyChanged("maxCantCuidadores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombrePromocion {
            get {
                return this.nombrePromocionField;
            }
            set {
                this.nombrePromocionField = value;
                this.RaisePropertyChanged("nombrePromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("psicologos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public psicologo[] psicologos {
            get {
                return this.psicologosField;
            }
            set {
                this.psicologosField = value;
                this.RaisePropertyChanged("psicologos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class tutor : usuario {
        
        private int activoTutorField;
        
        private int bajoRecursosField;
        
        private int diaField;
        
        private int dispositivosField;
        
        private int gestanteField;
        
        private grupo[] gruposField;
        
        private int redesSocialesField;
        
        private int tiposConexionField;
        
        private int turnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activoTutor {
            get {
                return this.activoTutorField;
            }
            set {
                this.activoTutorField = value;
                this.RaisePropertyChanged("activoTutor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int bajoRecursos {
            get {
                return this.bajoRecursosField;
            }
            set {
                this.bajoRecursosField = value;
                this.RaisePropertyChanged("bajoRecursos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int dispositivos {
            get {
                return this.dispositivosField;
            }
            set {
                this.dispositivosField = value;
                this.RaisePropertyChanged("dispositivos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int gestante {
            get {
                return this.gestanteField;
            }
            set {
                this.gestanteField = value;
                this.RaisePropertyChanged("gestante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("grupos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public grupo[] grupos {
            get {
                return this.gruposField;
            }
            set {
                this.gruposField = value;
                this.RaisePropertyChanged("grupos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int redesSociales {
            get {
                return this.redesSocialesField;
            }
            set {
                this.redesSocialesField = value;
                this.RaisePropertyChanged("redesSociales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int tiposConexion {
            get {
                return this.tiposConexionField;
            }
            set {
                this.tiposConexionField = value;
                this.RaisePropertyChanged("tiposConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(psicologo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tutor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class usuario : persona {
        
        private int activoField;
        
        private byte[] fotoPerfilField;
        
        private int idUsuarioField;
        
        private string passwordField;
        
        private int tipoField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fotoPerfil {
            get {
                return this.fotoPerfilField;
            }
            set {
                this.fotoPerfilField = value;
                this.RaisePropertyChanged("fotoPerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(psicologo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tutor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string celularField;
        
        private string correoField;
        
        private string dNIField;
        
        private distrito distritoField;
        
        private int edadField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private ushort generoField;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public distrito distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class distrito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idDistritoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                this.idDistritoField = value;
                this.RaisePropertyChanged("idDistrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class tema : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idField;
        
        private int id_curso_temaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id_curso_tema {
            get {
                return this.id_curso_temaField;
            }
            set {
                this.id_curso_temaField = value;
                this.RaisePropertyChanged("id_curso_tema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class semana : object, System.ComponentModel.INotifyPropertyChanged {
        
        private curso cursoField;
        
        private string descripcionField;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public curso curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class curso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantSemanasField;
        
        private string descripcionField;
        
        private int estadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private System.DateTime fechaInscripcionField;
        
        private bool fechaInscripcionFieldSpecified;
        
        private grupo[] gruposField;
        
        private int idCursoField;
        
        private requerimiento[] requerimientosField;
        
        private semana[] semanasField;
        
        private tema[] temasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantSemanas {
            get {
                return this.cantSemanasField;
            }
            set {
                this.cantSemanasField = value;
                this.RaisePropertyChanged("cantSemanas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaInscripcion {
            get {
                return this.fechaInscripcionField;
            }
            set {
                this.fechaInscripcionField = value;
                this.RaisePropertyChanged("fechaInscripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInscripcionSpecified {
            get {
                return this.fechaInscripcionFieldSpecified;
            }
            set {
                this.fechaInscripcionFieldSpecified = value;
                this.RaisePropertyChanged("fechaInscripcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("grupos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public grupo[] grupos {
            get {
                return this.gruposField;
            }
            set {
                this.gruposField = value;
                this.RaisePropertyChanged("grupos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requerimientos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public requerimiento[] requerimientos {
            get {
                return this.requerimientosField;
            }
            set {
                this.requerimientosField = value;
                this.RaisePropertyChanged("requerimientos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("semanas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public semana[] semanas {
            get {
                return this.semanasField;
            }
            set {
                this.semanasField = value;
                this.RaisePropertyChanged("semanas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("temas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public tema[] temas {
            get {
                return this.temasField;
            }
            set {
                this.temasField = value;
                this.RaisePropertyChanged("temas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class requerimiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idCursoReqField;
        
        private int idRequerimientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCursoReq {
            get {
                return this.idCursoReqField;
            }
            set {
                this.idCursoReqField = value;
                this.RaisePropertyChanged("idCursoReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idRequerimiento {
            get {
                return this.idRequerimientoField;
            }
            set {
                this.idRequerimientoField = value;
                this.RaisePropertyChanged("idRequerimiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class psicologo : usuario {
        
        private int activoPsicologoField;
        
        private curso[] cursosField;
        
        private grupo[] gruposField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activoPsicologo {
            get {
                return this.activoPsicologoField;
            }
            set {
                this.activoPsicologoField = value;
                this.RaisePropertyChanged("activoPsicologo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cursos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public curso[] cursos {
            get {
                return this.cursosField;
            }
            set {
                this.cursosField = value;
                this.RaisePropertyChanged("cursos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("grupos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public grupo[] grupos {
            get {
                return this.gruposField;
            }
            set {
                this.gruposField = value;
                this.RaisePropertyChanged("grupos");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGrupo", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarGrupoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCurso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.GrupoWS.grupo grupo;
        
        public insertarGrupoRequest() {
        }
        
        public insertarGrupoRequest(int idCurso, InterfazDATMA.GrupoWS.grupo grupo) {
            this.idCurso = idCurso;
            this.grupo = grupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGrupoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarGrupoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarGrupoResponse() {
        }
        
        public insertarGrupoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGrupo", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarGrupoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGrupo;
        
        public eliminarGrupoRequest() {
        }
        
        public eliminarGrupoRequest(int idGrupo) {
            this.idGrupo = idGrupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGrupoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarGrupoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarGrupoResponse() {
        }
        
        public eliminarGrupoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarGrupo", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarGrupoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.GrupoWS.grupo grupo;
        
        public modificarGrupoRequest() {
        }
        
        public modificarGrupoRequest(InterfazDATMA.GrupoWS.grupo grupo) {
            this.grupo = grupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarGrupoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarGrupoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarGrupoResponse() {
        }
        
        public modificarGrupoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGrupoTutor", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarGrupoTutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTutor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGrupo;
        
        public eliminarGrupoTutorRequest() {
        }
        
        public eliminarGrupoTutorRequest(int idTutor, int idGrupo) {
            this.idTutor = idTutor;
            this.idGrupo = idGrupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGrupoTutorResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarGrupoTutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarGrupoTutorResponse() {
        }
        
        public eliminarGrupoTutorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGrupoPsicologo", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarGrupoPsicologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPsicologo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGrupo;
        
        public insertarGrupoPsicologoRequest() {
        }
        
        public insertarGrupoPsicologoRequest(int idPsicologo, int idGrupo) {
            this.idPsicologo = idPsicologo;
            this.idGrupo = idGrupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGrupoPsicologoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarGrupoPsicologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarGrupoPsicologoResponse() {
        }
        
        public insertarGrupoPsicologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGrupoPsicologo", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarGrupoPsicologoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPsicologo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGrupo;
        
        public eliminarGrupoPsicologoRequest() {
        }
        
        public eliminarGrupoPsicologoRequest(int idPsicologo, int idGrupo) {
            this.idPsicologo = idPsicologo;
            this.idGrupo = idGrupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGrupoPsicologoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarGrupoPsicologoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarGrupoPsicologoResponse() {
        }
        
        public eliminarGrupoPsicologoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPsicologosPorIdGrupo", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarPsicologosPorIdGrupoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGrupo;
        
        public listarPsicologosPorIdGrupoRequest() {
        }
        
        public listarPsicologosPorIdGrupoRequest(int idGrupo) {
            this.idGrupo = idGrupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPsicologosPorIdGrupoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarPsicologosPorIdGrupoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.GrupoWS.psicologo[] @return;
        
        public listarPsicologosPorIdGrupoResponse() {
        }
        
        public listarPsicologosPorIdGrupoResponse(InterfazDATMA.GrupoWS.psicologo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarGrupoTutor", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarGrupoTutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTutor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numInfantes;
        
        public modificarGrupoTutorRequest() {
        }
        
        public modificarGrupoTutorRequest(int idTutor, int idGrupo, int numInfantes) {
            this.idTutor = idTutor;
            this.idGrupo = idGrupo;
            this.numInfantes = numInfantes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarGrupoTutorResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarGrupoTutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarGrupoTutorResponse() {
        }
        
        public modificarGrupoTutorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGrupoTutor", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarGrupoTutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTutor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numInfantes;
        
        public insertarGrupoTutorRequest() {
        }
        
        public insertarGrupoTutorRequest(int idTutor, int idGrupo, int numInfantes) {
            this.idTutor = idTutor;
            this.idGrupo = idGrupo;
            this.numInfantes = numInfantes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGrupoTutorResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarGrupoTutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarGrupoTutorResponse() {
        }
        
        public insertarGrupoTutorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTutoresPorIdGrupo", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarTutoresPorIdGrupoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGrupo;
        
        public listarTutoresPorIdGrupoRequest() {
        }
        
        public listarTutoresPorIdGrupoRequest(int idGrupo) {
            this.idGrupo = idGrupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTutoresPorIdGrupoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarTutoresPorIdGrupoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.GrupoWS.tutor[] @return;
        
        public listarTutoresPorIdGrupoResponse() {
        }
        
        public listarTutoresPorIdGrupoResponse(InterfazDATMA.GrupoWS.tutor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGrupoPorIdCurso", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarGrupoPorIdCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGrupo;
        
        public listarGrupoPorIdCursoRequest() {
        }
        
        public listarGrupoPorIdCursoRequest(int idGrupo) {
            this.idGrupo = idGrupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGrupoPorIdCursoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarGrupoPorIdCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.GrupoWS.grupo[] @return;
        
        public listarGrupoPorIdCursoResponse() {
        }
        
        public listarGrupoPorIdCursoResponse(InterfazDATMA.GrupoWS.grupo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GrupoWSChannel : InterfazDATMA.GrupoWS.GrupoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrupoWSClient : System.ServiceModel.ClientBase<InterfazDATMA.GrupoWS.GrupoWS>, InterfazDATMA.GrupoWS.GrupoWS {
        
        public GrupoWSClient() {
        }
        
        public GrupoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrupoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrupoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrupoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.insertarGrupoResponse InterfazDATMA.GrupoWS.GrupoWS.insertarGrupo(InterfazDATMA.GrupoWS.insertarGrupoRequest request) {
            return base.Channel.insertarGrupo(request);
        }
        
        public int insertarGrupo(int idCurso, InterfazDATMA.GrupoWS.grupo grupo) {
            InterfazDATMA.GrupoWS.insertarGrupoRequest inValue = new InterfazDATMA.GrupoWS.insertarGrupoRequest();
            inValue.idCurso = idCurso;
            inValue.grupo = grupo;
            InterfazDATMA.GrupoWS.insertarGrupoResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).insertarGrupo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.insertarGrupoResponse> InterfazDATMA.GrupoWS.GrupoWS.insertarGrupoAsync(InterfazDATMA.GrupoWS.insertarGrupoRequest request) {
            return base.Channel.insertarGrupoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.insertarGrupoResponse> insertarGrupoAsync(int idCurso, InterfazDATMA.GrupoWS.grupo grupo) {
            InterfazDATMA.GrupoWS.insertarGrupoRequest inValue = new InterfazDATMA.GrupoWS.insertarGrupoRequest();
            inValue.idCurso = idCurso;
            inValue.grupo = grupo;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).insertarGrupoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.eliminarGrupoResponse InterfazDATMA.GrupoWS.GrupoWS.eliminarGrupo(InterfazDATMA.GrupoWS.eliminarGrupoRequest request) {
            return base.Channel.eliminarGrupo(request);
        }
        
        public int eliminarGrupo(int idGrupo) {
            InterfazDATMA.GrupoWS.eliminarGrupoRequest inValue = new InterfazDATMA.GrupoWS.eliminarGrupoRequest();
            inValue.idGrupo = idGrupo;
            InterfazDATMA.GrupoWS.eliminarGrupoResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).eliminarGrupo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.eliminarGrupoResponse> InterfazDATMA.GrupoWS.GrupoWS.eliminarGrupoAsync(InterfazDATMA.GrupoWS.eliminarGrupoRequest request) {
            return base.Channel.eliminarGrupoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.eliminarGrupoResponse> eliminarGrupoAsync(int idGrupo) {
            InterfazDATMA.GrupoWS.eliminarGrupoRequest inValue = new InterfazDATMA.GrupoWS.eliminarGrupoRequest();
            inValue.idGrupo = idGrupo;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).eliminarGrupoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.modificarGrupoResponse InterfazDATMA.GrupoWS.GrupoWS.modificarGrupo(InterfazDATMA.GrupoWS.modificarGrupoRequest request) {
            return base.Channel.modificarGrupo(request);
        }
        
        public int modificarGrupo(InterfazDATMA.GrupoWS.grupo grupo) {
            InterfazDATMA.GrupoWS.modificarGrupoRequest inValue = new InterfazDATMA.GrupoWS.modificarGrupoRequest();
            inValue.grupo = grupo;
            InterfazDATMA.GrupoWS.modificarGrupoResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).modificarGrupo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.modificarGrupoResponse> InterfazDATMA.GrupoWS.GrupoWS.modificarGrupoAsync(InterfazDATMA.GrupoWS.modificarGrupoRequest request) {
            return base.Channel.modificarGrupoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.modificarGrupoResponse> modificarGrupoAsync(InterfazDATMA.GrupoWS.grupo grupo) {
            InterfazDATMA.GrupoWS.modificarGrupoRequest inValue = new InterfazDATMA.GrupoWS.modificarGrupoRequest();
            inValue.grupo = grupo;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).modificarGrupoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.eliminarGrupoTutorResponse InterfazDATMA.GrupoWS.GrupoWS.eliminarGrupoTutor(InterfazDATMA.GrupoWS.eliminarGrupoTutorRequest request) {
            return base.Channel.eliminarGrupoTutor(request);
        }
        
        public int eliminarGrupoTutor(int idTutor, int idGrupo) {
            InterfazDATMA.GrupoWS.eliminarGrupoTutorRequest inValue = new InterfazDATMA.GrupoWS.eliminarGrupoTutorRequest();
            inValue.idTutor = idTutor;
            inValue.idGrupo = idGrupo;
            InterfazDATMA.GrupoWS.eliminarGrupoTutorResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).eliminarGrupoTutor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.eliminarGrupoTutorResponse> InterfazDATMA.GrupoWS.GrupoWS.eliminarGrupoTutorAsync(InterfazDATMA.GrupoWS.eliminarGrupoTutorRequest request) {
            return base.Channel.eliminarGrupoTutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.eliminarGrupoTutorResponse> eliminarGrupoTutorAsync(int idTutor, int idGrupo) {
            InterfazDATMA.GrupoWS.eliminarGrupoTutorRequest inValue = new InterfazDATMA.GrupoWS.eliminarGrupoTutorRequest();
            inValue.idTutor = idTutor;
            inValue.idGrupo = idGrupo;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).eliminarGrupoTutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.insertarGrupoPsicologoResponse InterfazDATMA.GrupoWS.GrupoWS.insertarGrupoPsicologo(InterfazDATMA.GrupoWS.insertarGrupoPsicologoRequest request) {
            return base.Channel.insertarGrupoPsicologo(request);
        }
        
        public int insertarGrupoPsicologo(int idPsicologo, int idGrupo) {
            InterfazDATMA.GrupoWS.insertarGrupoPsicologoRequest inValue = new InterfazDATMA.GrupoWS.insertarGrupoPsicologoRequest();
            inValue.idPsicologo = idPsicologo;
            inValue.idGrupo = idGrupo;
            InterfazDATMA.GrupoWS.insertarGrupoPsicologoResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).insertarGrupoPsicologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.insertarGrupoPsicologoResponse> InterfazDATMA.GrupoWS.GrupoWS.insertarGrupoPsicologoAsync(InterfazDATMA.GrupoWS.insertarGrupoPsicologoRequest request) {
            return base.Channel.insertarGrupoPsicologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.insertarGrupoPsicologoResponse> insertarGrupoPsicologoAsync(int idPsicologo, int idGrupo) {
            InterfazDATMA.GrupoWS.insertarGrupoPsicologoRequest inValue = new InterfazDATMA.GrupoWS.insertarGrupoPsicologoRequest();
            inValue.idPsicologo = idPsicologo;
            inValue.idGrupo = idGrupo;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).insertarGrupoPsicologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.eliminarGrupoPsicologoResponse InterfazDATMA.GrupoWS.GrupoWS.eliminarGrupoPsicologo(InterfazDATMA.GrupoWS.eliminarGrupoPsicologoRequest request) {
            return base.Channel.eliminarGrupoPsicologo(request);
        }
        
        public int eliminarGrupoPsicologo(int idPsicologo, int idGrupo) {
            InterfazDATMA.GrupoWS.eliminarGrupoPsicologoRequest inValue = new InterfazDATMA.GrupoWS.eliminarGrupoPsicologoRequest();
            inValue.idPsicologo = idPsicologo;
            inValue.idGrupo = idGrupo;
            InterfazDATMA.GrupoWS.eliminarGrupoPsicologoResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).eliminarGrupoPsicologo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.eliminarGrupoPsicologoResponse> InterfazDATMA.GrupoWS.GrupoWS.eliminarGrupoPsicologoAsync(InterfazDATMA.GrupoWS.eliminarGrupoPsicologoRequest request) {
            return base.Channel.eliminarGrupoPsicologoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.eliminarGrupoPsicologoResponse> eliminarGrupoPsicologoAsync(int idPsicologo, int idGrupo) {
            InterfazDATMA.GrupoWS.eliminarGrupoPsicologoRequest inValue = new InterfazDATMA.GrupoWS.eliminarGrupoPsicologoRequest();
            inValue.idPsicologo = idPsicologo;
            inValue.idGrupo = idGrupo;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).eliminarGrupoPsicologoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoResponse InterfazDATMA.GrupoWS.GrupoWS.listarPsicologosPorIdGrupo(InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoRequest request) {
            return base.Channel.listarPsicologosPorIdGrupo(request);
        }
        
        public InterfazDATMA.GrupoWS.psicologo[] listarPsicologosPorIdGrupo(int idGrupo) {
            InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoRequest inValue = new InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoRequest();
            inValue.idGrupo = idGrupo;
            InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).listarPsicologosPorIdGrupo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoResponse> InterfazDATMA.GrupoWS.GrupoWS.listarPsicologosPorIdGrupoAsync(InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoRequest request) {
            return base.Channel.listarPsicologosPorIdGrupoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoResponse> listarPsicologosPorIdGrupoAsync(int idGrupo) {
            InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoRequest inValue = new InterfazDATMA.GrupoWS.listarPsicologosPorIdGrupoRequest();
            inValue.idGrupo = idGrupo;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).listarPsicologosPorIdGrupoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.modificarGrupoTutorResponse InterfazDATMA.GrupoWS.GrupoWS.modificarGrupoTutor(InterfazDATMA.GrupoWS.modificarGrupoTutorRequest request) {
            return base.Channel.modificarGrupoTutor(request);
        }
        
        public int modificarGrupoTutor(int idTutor, int idGrupo, int numInfantes) {
            InterfazDATMA.GrupoWS.modificarGrupoTutorRequest inValue = new InterfazDATMA.GrupoWS.modificarGrupoTutorRequest();
            inValue.idTutor = idTutor;
            inValue.idGrupo = idGrupo;
            inValue.numInfantes = numInfantes;
            InterfazDATMA.GrupoWS.modificarGrupoTutorResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).modificarGrupoTutor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.modificarGrupoTutorResponse> InterfazDATMA.GrupoWS.GrupoWS.modificarGrupoTutorAsync(InterfazDATMA.GrupoWS.modificarGrupoTutorRequest request) {
            return base.Channel.modificarGrupoTutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.modificarGrupoTutorResponse> modificarGrupoTutorAsync(int idTutor, int idGrupo, int numInfantes) {
            InterfazDATMA.GrupoWS.modificarGrupoTutorRequest inValue = new InterfazDATMA.GrupoWS.modificarGrupoTutorRequest();
            inValue.idTutor = idTutor;
            inValue.idGrupo = idGrupo;
            inValue.numInfantes = numInfantes;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).modificarGrupoTutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.insertarGrupoTutorResponse InterfazDATMA.GrupoWS.GrupoWS.insertarGrupoTutor(InterfazDATMA.GrupoWS.insertarGrupoTutorRequest request) {
            return base.Channel.insertarGrupoTutor(request);
        }
        
        public int insertarGrupoTutor(int idTutor, int idGrupo, int numInfantes) {
            InterfazDATMA.GrupoWS.insertarGrupoTutorRequest inValue = new InterfazDATMA.GrupoWS.insertarGrupoTutorRequest();
            inValue.idTutor = idTutor;
            inValue.idGrupo = idGrupo;
            inValue.numInfantes = numInfantes;
            InterfazDATMA.GrupoWS.insertarGrupoTutorResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).insertarGrupoTutor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.insertarGrupoTutorResponse> InterfazDATMA.GrupoWS.GrupoWS.insertarGrupoTutorAsync(InterfazDATMA.GrupoWS.insertarGrupoTutorRequest request) {
            return base.Channel.insertarGrupoTutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.insertarGrupoTutorResponse> insertarGrupoTutorAsync(int idTutor, int idGrupo, int numInfantes) {
            InterfazDATMA.GrupoWS.insertarGrupoTutorRequest inValue = new InterfazDATMA.GrupoWS.insertarGrupoTutorRequest();
            inValue.idTutor = idTutor;
            inValue.idGrupo = idGrupo;
            inValue.numInfantes = numInfantes;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).insertarGrupoTutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoResponse InterfazDATMA.GrupoWS.GrupoWS.listarTutoresPorIdGrupo(InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoRequest request) {
            return base.Channel.listarTutoresPorIdGrupo(request);
        }
        
        public InterfazDATMA.GrupoWS.tutor[] listarTutoresPorIdGrupo(int idGrupo) {
            InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoRequest inValue = new InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoRequest();
            inValue.idGrupo = idGrupo;
            InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).listarTutoresPorIdGrupo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoResponse> InterfazDATMA.GrupoWS.GrupoWS.listarTutoresPorIdGrupoAsync(InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoRequest request) {
            return base.Channel.listarTutoresPorIdGrupoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoResponse> listarTutoresPorIdGrupoAsync(int idGrupo) {
            InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoRequest inValue = new InterfazDATMA.GrupoWS.listarTutoresPorIdGrupoRequest();
            inValue.idGrupo = idGrupo;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).listarTutoresPorIdGrupoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.GrupoWS.listarGrupoPorIdCursoResponse InterfazDATMA.GrupoWS.GrupoWS.listarGrupoPorIdCurso(InterfazDATMA.GrupoWS.listarGrupoPorIdCursoRequest request) {
            return base.Channel.listarGrupoPorIdCurso(request);
        }
        
        public InterfazDATMA.GrupoWS.grupo[] listarGrupoPorIdCurso(int idGrupo) {
            InterfazDATMA.GrupoWS.listarGrupoPorIdCursoRequest inValue = new InterfazDATMA.GrupoWS.listarGrupoPorIdCursoRequest();
            inValue.idGrupo = idGrupo;
            InterfazDATMA.GrupoWS.listarGrupoPorIdCursoResponse retVal = ((InterfazDATMA.GrupoWS.GrupoWS)(this)).listarGrupoPorIdCurso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.listarGrupoPorIdCursoResponse> InterfazDATMA.GrupoWS.GrupoWS.listarGrupoPorIdCursoAsync(InterfazDATMA.GrupoWS.listarGrupoPorIdCursoRequest request) {
            return base.Channel.listarGrupoPorIdCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.GrupoWS.listarGrupoPorIdCursoResponse> listarGrupoPorIdCursoAsync(int idGrupo) {
            InterfazDATMA.GrupoWS.listarGrupoPorIdCursoRequest inValue = new InterfazDATMA.GrupoWS.listarGrupoPorIdCursoRequest();
            inValue.idGrupo = idGrupo;
            return ((InterfazDATMA.GrupoWS.GrupoWS)(this)).listarGrupoPorIdCursoAsync(inValue);
        }
    }
}
