//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazDATMA.ReporteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.datmasoft.datma.pe/", ConfigurationName="ReporteWS.ReporteWS")]
    public interface ReporteWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.datmasoft.datma.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/ReporteWS/reportePreferenciasRequest", ReplyAction="http://services.datmasoft.datma.pe/ReporteWS/reportePreferenciasResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.ReporteWS.reportePreferenciasResponse reportePreferencias(InterfazDATMA.ReporteWS.reportePreferenciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/ReporteWS/reportePreferenciasRequest", ReplyAction="http://services.datmasoft.datma.pe/ReporteWS/reportePreferenciasResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.ReporteWS.reportePreferenciasResponse> reportePreferenciasAsync(InterfazDATMA.ReporteWS.reportePreferenciasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.datmasoft.datma.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/ReporteWS/reportePsicologosRequest", ReplyAction="http://services.datmasoft.datma.pe/ReporteWS/reportePsicologosResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.ReporteWS.reportePsicologosResponse reportePsicologos(InterfazDATMA.ReporteWS.reportePsicologosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/ReporteWS/reportePsicologosRequest", ReplyAction="http://services.datmasoft.datma.pe/ReporteWS/reportePsicologosResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.ReporteWS.reportePsicologosResponse> reportePsicologosAsync(InterfazDATMA.ReporteWS.reportePsicologosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reportePreferencias", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class reportePreferenciasRequest {
        
        public reportePreferenciasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reportePreferenciasResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class reportePreferenciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public reportePreferenciasResponse() {
        }
        
        public reportePreferenciasResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reportePsicologos", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class reportePsicologosRequest {
        
        public reportePsicologosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reportePsicologosResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class reportePsicologosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public reportePsicologosResponse() {
        }
        
        public reportePsicologosResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteWSChannel : InterfazDATMA.ReporteWS.ReporteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteWSClient : System.ServiceModel.ClientBase<InterfazDATMA.ReporteWS.ReporteWS>, InterfazDATMA.ReporteWS.ReporteWS {
        
        public ReporteWSClient() {
        }
        
        public ReporteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.ReporteWS.reportePreferenciasResponse InterfazDATMA.ReporteWS.ReporteWS.reportePreferencias(InterfazDATMA.ReporteWS.reportePreferenciasRequest request) {
            return base.Channel.reportePreferencias(request);
        }
        
        public byte[] reportePreferencias() {
            InterfazDATMA.ReporteWS.reportePreferenciasRequest inValue = new InterfazDATMA.ReporteWS.reportePreferenciasRequest();
            InterfazDATMA.ReporteWS.reportePreferenciasResponse retVal = ((InterfazDATMA.ReporteWS.ReporteWS)(this)).reportePreferencias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.ReporteWS.reportePreferenciasResponse> InterfazDATMA.ReporteWS.ReporteWS.reportePreferenciasAsync(InterfazDATMA.ReporteWS.reportePreferenciasRequest request) {
            return base.Channel.reportePreferenciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.ReporteWS.reportePreferenciasResponse> reportePreferenciasAsync() {
            InterfazDATMA.ReporteWS.reportePreferenciasRequest inValue = new InterfazDATMA.ReporteWS.reportePreferenciasRequest();
            return ((InterfazDATMA.ReporteWS.ReporteWS)(this)).reportePreferenciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.ReporteWS.reportePsicologosResponse InterfazDATMA.ReporteWS.ReporteWS.reportePsicologos(InterfazDATMA.ReporteWS.reportePsicologosRequest request) {
            return base.Channel.reportePsicologos(request);
        }
        
        public byte[] reportePsicologos() {
            InterfazDATMA.ReporteWS.reportePsicologosRequest inValue = new InterfazDATMA.ReporteWS.reportePsicologosRequest();
            InterfazDATMA.ReporteWS.reportePsicologosResponse retVal = ((InterfazDATMA.ReporteWS.ReporteWS)(this)).reportePsicologos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.ReporteWS.reportePsicologosResponse> InterfazDATMA.ReporteWS.ReporteWS.reportePsicologosAsync(InterfazDATMA.ReporteWS.reportePsicologosRequest request) {
            return base.Channel.reportePsicologosAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.ReporteWS.reportePsicologosResponse> reportePsicologosAsync() {
            InterfazDATMA.ReporteWS.reportePsicologosRequest inValue = new InterfazDATMA.ReporteWS.reportePsicologosRequest();
            return ((InterfazDATMA.ReporteWS.ReporteWS)(this)).reportePsicologosAsync(inValue);
        }
    }
}
